import{a as f,S as p,i as a}from"./assets/vendor-527658dd.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function o(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(r){if(r.ep)return;r.ep=!0;const s=o(r);fetch(r.href,s)}})();const b="42454859-ed417d87285a7db1b1c819d54",w="https://pixabay.com/api/";async function y(t,e){try{const o=new URLSearchParams({key:b,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:e,per_page:15}),{data:n}=await f.get(`${w}?${o}`);if(!n||n.hits.length===0)throw new Error("No images found");return n.hits}catch(o){throw new Error(`Error fetching data: ${o.message}`)}}const L=document.querySelector(".loader"),E=document.querySelector(".gallery"),v=new p(".gallery a");function h(t){if(L.style.display="none",t.length===0){a.show({message:"Sorry, there are no images matching </br> your search query. Please try again!",messageColor:"white",backgroundColor:"#EF4040",position:"topRight",iconColor:"white",close:!0,displayMode:1,timeout:3e3});return}t.forEach(e=>{const o=document.createElement("div");o.classList.add("card"),o.innerHTML=`
        <li><a href="${e.largeImageURL}" data-lightbox="gallery">
                <img src="${e.webformatURL}" alt="${e.tags}">
            </a>
            <div>
            <p> <span>Likes:</span> <br/> ${e.likes}</p>
            <p> <span>Views:</span> <br/> ${e.views}</p>
            <p> <span>Comments:</span> <br/> ${e.comments}</p>
            <p> <span>Downloads:</span> <br/> ${e.downloads}</p>
            </div>
            </li>
        `,E.appendChild(o)}),v.refresh()}const S=document.querySelector(".form"),d=document.getElementById("search-img"),u=document.querySelector(".loader"),$=document.querySelector(".gallery"),i=document.querySelector(".load-btn");let c=1;u.style.display="none";i.style.display="none";const g=new p(".gallery a");i.addEventListener("click",async function(){try{const t=d.value.trim(),e=await y(t,c);h(e),c++,m(e),q(),g.refresh()}catch(t){console.error("Error fetching data:",t),a.error({position:"topRight",title:"Error",message:"An error occurred. Please try again."})}});S.addEventListener("submit",async function(t){t.preventDefault(),c=1;const e=d.value.trim();if(e===""){a.error({title:"Error",position:"topRight",message:"Please enter a search term"});return}$.innerHTML="";try{u.style.display="block";const o=await y(e,c);h(o),d.value="",m(o),g.refresh()}catch(o){console.error("Error fetching data:",o),a.error({title:"Error",position:"topRight",message:"An error occurred. Please try again."})}finally{u.style.display="none"}});function m(t){t.length===15?i.style.display="block":i.style.display="none"}function q(){const e=document.querySelector(".card").getBoundingClientRect().height*2;window.scrollBy({top:e,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
