import{a as f,S as u,i as n}from"./assets/vendor-527658dd.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))a(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function t(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(r){if(r.ep)return;r.ep=!0;const s=t(r);fetch(r.href,s)}})();const b="42454859-ed417d87285a7db1b1c819d54",w="https://pixabay.com/api/";async function y(o,e){try{const t=new URLSearchParams({key:b,q:o,image_type:"photo",orientation:"horizontal",safesearch:"true",page:e,per_page:15}),{data:a}=await f.get(`${w}?${t}`);if(!a||a.hits.length===0)throw new Error("No images found");return a.hits}catch(t){throw new Error(`Error fetching data: ${t.message}`)}}const L=document.querySelector(".loader"),E=document.querySelector(".gallery"),$=new u(".gallery a");function h(o){if(L.style.display="none",o.length===0){n.show({message:"Sorry, there are no images matching </br> your search query. Please try again!",messageColor:"white",backgroundColor:"#EF4040",position:"topRight",iconColor:"white",close:!0,displayMode:1,timeout:3e3});return}o.forEach(e=>{const t=document.createElement("div");t.classList.add("card"),t.innerHTML=`
        <li><a href="${e.largeImageURL}" data-lightbox="gallery">
                <img src="${e.webformatURL}" alt="${e.tags}">
            </a>
            <div>
            <p> <span>Likes:</span> <br/> ${e.likes}</p>
            <p> <span>Views:</span> <br/> ${e.views}</p>
            <p> <span>Comments:</span> <br/> ${e.comments}</p>
            <p> <span>Downloads:</span> <br/> ${e.downloads}</p>
            </div>
            </li>
        `,E.appendChild(t)}),$.refresh()}const v=document.querySelector(".form"),d=document.getElementById("search-img"),p=document.querySelector(".loader"),P=document.querySelector(".gallery"),i=document.querySelector(".load-btn");let c=1,S=15;const q=Math.ceil(100/S);p.style.display="none";i.style.display="none";const g=new u(".gallery a");i.addEventListener("click",async function(){if(c>q)return i.style.display="none",n.error({position:"topRight",message:"We're sorry, there are no more posts to load"});try{const o=d.value.trim(),e=await y(o,c);h(e),c++,m(e),g.refresh()}catch(o){console.error("Error fetching data:",o),n.error({position:"topRight",title:"Error",message:"An error occurred. Please try again."})}});v.addEventListener("submit",async function(o){o.preventDefault();const e=d.value.trim();if(e===""){n.error({title:"Error",position:"topRight",message:"Please enter a search term"});return}p.style.display="block",P.innerHTML="";try{const t=await y(e,c);h(t),d.value="",m(t),g.refresh()}catch(t){console.error("Error fetching data:",t),n.error({title:"Error",position:"topRight",message:"An error occurred. Please try again."})}finally{p.style.display="none"}});function m(o){o.length===15?i.style.display="block":i.style.display="none"}
//# sourceMappingURL=commonHelpers.js.map
