import{a as b,S as y,i}from"./assets/vendor-527658dd.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&n(d)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const w="42454859-ed417d87285a7db1b1c819d54",L="https://pixabay.com/api/";async function h(r,e){try{const s=new URLSearchParams({key:w,q:r,image_type:"photo",orientation:"horizontal",safesearch:"true",page:e,per_page:15}),{data:n}=await b.get(`${L}?${s}`);if(!n||n.hits.length===0)throw new Error("No images found");return n.hits}catch(s){throw new Error(`Error fetching data: ${s.message}`)}}const E=document.querySelector(".loader"),S=document.querySelector(".gallery"),$=new y(".gallery a");function g(r){if(E.style.display="none",r.length===0){i.show({message:"Sorry, there are no images matching </br> your search query. Please try again!",messageColor:"white",backgroundColor:"#EF4040",position:"topRight",iconColor:"white",close:!0,displayMode:1,timeout:3e3});return}r.forEach(e=>{const s=document.createElement("div");s.classList.add("card"),s.innerHTML=`
        <li><a href="${e.largeImageURL}" data-lightbox="gallery">
                <img src="${e.webformatURL}" alt="${e.tags}">
            </a>
            <div>
            <p> <span>Likes:</span> <br/> ${e.likes}</p>
            <p> <span>Views:</span> <br/> ${e.views}</p>
            <p> <span>Comments:</span> <br/> ${e.comments}</p>
            <p> <span>Downloads:</span> <br/> ${e.downloads}</p>
            </div>
            </li>
        `,S.appendChild(s)}),$.refresh()}const v=document.querySelector(".form"),p=document.getElementById("search-img"),u=document.querySelector(".loader"),q=document.querySelector(".gallery"),c=document.querySelector(".load-btn");let l=1,a;u.style.display="none";c.style.display="none";const m=new y(".gallery a");c.addEventListener("click",async function(){l+=1;try{const r=await h(a,l);g(r),f(r),P(),m.refresh()}catch(r){console.error("Error fetching data:",r),i.error({position:"topRight",title:"Error",message:"An error occurred. Please try again."})}});v.addEventListener("submit",async function(r){if(r.preventDefault(),l=1,a=p.value.trim(),a===""){i.error({title:"Error",position:"topRight",message:"Please enter a search term"});return}q.innerHTML="";try{u.style.display="block";const e=await h(a,l);g(e),p.value="",f(e),m.refresh()}catch(e){console.error("Error fetching data:",e),i.error({title:"Error",position:"topRight",message:"An error occurred. Please try again."})}finally{u.style.display="none"}});function f(r){r.length===15?c.style.display="block":c.style.display="none"}function P(){const e=document.querySelector(".card").getBoundingClientRect().height*2;window.scrollBy({top:e,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
